spring:
  datasource:
    url: jdbc:mysql://localhost:3306/computer_store?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lx200288
  application:
    name: nacos-user
  cloud:
    nacos:
      discovery:
        server_addr: localhost:8848
dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false
#seata:
#  tx-service-group: csmall_group
#  service:
#    vgroup-mapping:
#      csmall_group: default
#    grouplist:
#      default: localhost:8091
