server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      # routes 是一个数组类型的变量(yml文件中"- ..."表示当前配置的是数组元素)
      routes:
        - id: mall-order
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: mall-/car
          uri: lb:///car
          predicates:
            - Path=//car/**
        - id: mall-user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: mall-category
          uri: lb://category
          predicates:
              - Path=/category/**
        - id: mall-address
          uri: lb://address
          predicates:
            - Path=/address/**
        - id: mall-product
          uri: lb://product
          predicates:
            - Path=/product/**