server:
  port: 20001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/computer_store?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lx200288
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: carservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        # 仪表台所在位置
        dashboard: localhost:8080
dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false
main:
  allow-circular-references: true